export let questions = [
    ["What is the policy of EAFab Corporation?", "What are EAFab’s most valuable resources?", "What will the Safety and Health Program assist in?"],
    ["What are the three instances in which training will occur?", "What are two Safety and Health Trainings provided to employees?", "What is the purpose of the hazard Communication Program?"],
    ["What should an employee do if they see a hazard or unsafe condition on the job?", "Where are postings such as Safety and Health protection and OSHA citations displayed?", "When will employees have access to the Employee Safety Handbook?"],
    ["Who is the appointed Safety Committee chairperson?", "What is the purpose of The Safety Committee?", "What is one responsibility of The Safety Committee?"],
    ["Who will act as program coordinator?", "Where does EAFab maintain a list of chemicals and their corresponding SDS?", "To whom should employees immediately report unknown or unnamed chemicals?"],
    ["When will employees complete training in hazard identification and risk assessment?", "How many levels are on the Risk Severity Index?", "When is the Hazard Assessment process repeated?"],
    ["Where are emergency escape procedures and route assignments posted?", "How should a chemical spill/leak be reported?", "Where should an employee go following an evacuation?"],
    ["What are the flame cutting minimum PPE requirements?", "What are the welding minimum PPE requirements?", "When is protective eyewear necessary?"],
    ["What types of machinery does the Machinery Tag Out Program apply to?", "What should be done to machinery before performing maintenance?", "How is a lock out performed?"],
    ["Before removing a tag or lock, from whom is approval required?", "Before removing a tag or lock, from whom is approval required?", "Who is responsible for verifying training is complete for this program?"],
    ["Who should potential safety and workplace health hazards be reported to?", "Hazards that do not cause imminent harm are to be abated in how many days?", "How should employees keep their work areas?"],
    ["What must management give warnings of?", "Who will fill out the Liability Report Form in the event of an accident?", "Who is responsible for fixing or repairing items?"],
    ["When might this form be used?", "What is the purpose of this form?", "Who can fill out this form?"],
    ["What are the objectives that the EAP will meet?", "When will training on the EAP take place?", "What action must be taken when a fire is reported?"],
    ["What are reasons that an OSHA Inspection may be conducted?", "What are the steps to be taken when admitting an OSHA officer?", "What are the three parts of the OSHA inspection?"],
    ["What are the four classifications of hazardous chemicals?", "What is the procedure when a hazardous material spill occurs?", "What should employees in contact with hazardous material do?"],
    ["What are the responsibilities of the employee when operating a motor vehicle?", "What are the operating rules and practices?", "What are the steps to be taken in the case of an accident?"],
    ["What are the definitions applicable to an “accident”?", "What are the prohibited drugs?", "Which individuals are subject to drug testing?"],
    ["What requirements must employees meet before they are “certified” to operate a powered industrial truck?", "What instruction will the supervisor provide on-the-job?", "What test is used to certify the employee?"],
    ["What are the responsibilities of the supervisor?", "What are the responsibilities of the employee?", "What are the shop procedures?"],
    ["What are the procedures when using pressure equipment?", "What protective equipment must be used when painting?", "What is the procedure when there are spills?"],
    ["What are the ventilation systems utilized in fire prevention?", "What are the requirements for electrical wiring and equipment?", "What are the requirements for storage and handling?"],
    ["What is the company incident reporting system designed to do?", "What are the responsibilities of the different individuals in the company?", "Who is required to maintain their own OSHA 300 Log?"],
    ["What items must employees disinfect?", "What are the guidelines for inbound parts/materials/packages?", "What is the procedure for disinfecting a forklift, and how often should it be done?"]
]
