export let questions = [
    ["What are the three instances in which training will occur?", "What are two Safety and Health Trainings provided to employees?", "What is the purpose of the hazard Communication Program?"],
    ["What should an employee do if they see a hazard or unsafe condition on the job?", "Where are postings such as Safety and Health protection and OSHA citations displayed?", "When will employees have access to the Employee Safety Handbook?"],
    ["Who is the appointed Safety Committee chairperson?", "What is the purpose of The Safety Committee?", "What is one responsibility of The Safety Committee?"],
    ["Who will act as program coordinator?", "Where does EAFab maintain a list of chemicals and their corresponding SDS?", "To whom should employees immediately report unknown or unnamed chemicals?"],
    ["When will employees complete training in hazard identification and risk assessment?", "How many levels are on the Risk Severity Index?", "When is the Hazard Assessment process repeated?"],
    ["Where are emergency escape procedures and route assignments posted?", "How should a chemical spill/leak be reported?", "Where should an employee go following an evacuation?"],
    ["What are the flame cutting minimum PPE requirements?", "What are the welding minimum PPE requirements?", "When is protective eyewear necessary?"],
    ["What types of machinery does the Machinery Tag Out Program apply to?", "What should be done to machinery before performing maintenance?", "How is a lock out performed?"],
    ["q1", "q2", "q3"],
    ["q1", "q2", "q3"],
    ["q1", "q2", "q3"],
    ["q1", "q2", "q3"],
    ["q1", "q2", "q3"],
    ["q1", "q2", "q3"],
    ["q1", "q2", "q3"],
    ["q1", "q2", "q3"],
    ["q1", "q2", "q3"],
    ["q1", "q2", "q3"],
    ["q1", "q2", "q3"],
    ["q1", "q2", "q3"],
    ["q1", "q2", "q3"],
    ["q1", "q2", "q3"],
    ["q1", "q2", "q3"],
    ["q1", "q2", "q3"]
]
